"""Add articles & comments

Revision ID: 0001
Revises: 
Create Date: 2024-03-04 14:20:07.175144

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
                    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('image_url', sa.TEXT(), nullable=True),
                    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('body', sa.TEXT(), nullable=False),
                    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DATETIME(),
                              server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('article_comments',
                    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('article_id', sa.BIGINT(), nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('body', sa.TEXT(), nullable=False),
                    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
                    sa.PrimaryKeyConstraint('id', 'article_id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_comments')
    op.drop_table('articles')
    # ### end Alembic commands ###
